### ISSUE TITLE
请问在CIFAR-10上使用的ResNet模型结构是什么呢？/ What is the structure of the ResNet model used on CIFAR-10?

### ISSUE THREAD

**Issue by SummerWJLiu** [jingyang2017/KD_SRRL#1]
您好！我目前在试图复现这篇论文的实验结果，可是对于CIFAR-10上使用的ResNet网络的结构不是很明白，请问其中的ResNet-18使用的是ResNet原论文中针对ImageNet数据集的版本吗？

Excuse me. I am currently trying to reproduce the experimental results of this paper, but I am not very clear about the structure of the ResNet network used on CIFAR-10. Does ResNet-18 use the version for the ImageNet dataset in the original ResNet paper?

**Comment by jingyang2017** [comment]
I follow this https://github.com/clovaai/overhaul-distillation/blob/master/CIFAR-100/models/ResNet.py.

**Comment by SummerWJLiu** [comment]
Thank you very much for your quick reply. It helps a lot. 
Can I get the ResNet-8,14,18,26,34 for CIFAR-10 by just changing the `depth` parameter?

**Comment by jingyang2017** [comment]
I think so.

**Comment by jingyang2017** [comment]
I think so.
