### ISSUE TITLE
Cannot find args.weight 

### ISSUE THREAD

**Issue by ziyuwwang** [jingyang2017/KD_SRRL#2]
Thanks for the release! I tried the code but found that there exists some bugs in current version. For example, the setting item "args.weight" in "train_imagenet_distillation.py" cannot be found. I would be appreciate if you could fix the bugs and provide the hyper-parameters which could be used to reproduce the results in the paper.

**Comment by jingyang2017** [comment]
I have updated the args.weight. Please check the current version.
