### ISSUE TITLE
Hi, could you upload CIFAR training script?

### ISSUE THREAD

**Issue by DeepLearningHB** [jingyang2017/KD_SRRL#3]
Hi there, 

I've tried make a cifar version of this method. but, my script was not able to reproduce your performance from paper.
Most of model showed lower performance than CRD paper..
I wanna do experiment by using your original script. 
Could you upload CIFAR-100 setting for this method?

Thanks.

**Comment by jingyang2017** [comment]
It is a bit tricky to find the best parameters for the different teacher-student pairs. For the pairs lower than the CRD ones, could you try alpha =1, beta=1,alpha =1, beta=5, alpha=10,beta=1 weights. I did a grid search for different pairs but did not have all records in hand.

**Comment by jingyang2017** [comment]
> Hi there,
> 
> I've tried make a cifar version of this method. but, my script was not able to reproduce your performance from paper.
> Most of model showed lower performance than CRD paper..
> I wanna do experiment by using your original script.
> Could you upload CIFAR-100 setting for this method?
> 
> Thanks.

It is a bit tricky to find the best parameters for the different teacher-student pairs. For the pairs lower than the CRD ones, could you try alpha =1, beta=1,alpha =1, beta=5, alpha=10,beta=1 weights. I did a grid search for different pairs but did not have all records in hand. Thanks.
