### ISSUE TITLE
Hi, I have a question about regression setting

### ISSUE THREAD

**Issue by DeepLearningHB** [jingyang2017/KD_SRRL#4]
Hi there. 
I'm wondering how you implement knowledge distillation in regression.
As you know, Hinton et al. distillation said that softmax representation contains intra-class information. 
That's why I think it's hard to implement the code with respect to regression problem.
But, you experimented facial keypoint detection by using Hinton KD..
How did you code it? 
Thanks.

Regards.

**Comment by jingyang2017** [comment]
As is described in Section 5.4 in the KD_SRRL. KD is adapted by using an L2 loss instead of a KL loss to measure the discrepancy between the teacher and student predictions. I hope this will solve your concern.

**Comment by jingyang2017** [comment]
> Hi there.
> I'm wondering how you implement knowledge distillation in regression.
> As you know, Hinton et al. distillation said that softmax representation contains intra-class information.
> That's why I think it's hard to implement the code with respect to regression problem.
> But, you experimented facial keypoint detection by using Hinton KD..
> How did you code it?
> Thanks.
> 
> Regards.

As is described in Section 5.4 in the KD_SRRL. KD is adapted by using an L2 loss instead of a KL loss to measure the discrepancy between the teacher and student predictions. I hope this will solve your concern.

**Comment by simoneangarano** [comment]
Hi,
where's the code you used for regression? e.g. what API did you use for WFLW?
thanks!
