### ISSUE TITLE
About gpu nums and training log

### ISSUE THREAD

**Issue by ofishhaha** [jingyang2017/KD_SRRL#5]
Thanks for the release! I noticed that the batch size is 512 here. And I wonder how many gpu did u use?
I just want to follow ur training process. Would u please share a training log, so we can find if there is a wrong setting in the beginning of training.

**Comment by jingyang2017** [comment]
> Thanks for the release! I noticed that the batch size is 512 here. And I wonder how many gpu did u use?
> I just want to follow ur training process. Would u please share a training log, so we can find if there is a wrong setting in the beginning of training.

I have used 8 GPUs in training. The training logs are in https://drive.google.com/drive/folders/19OnwUad63-ITXL2TxguRdyP0KtKJIfgI?usp=sharing.
